name: theostos/coq-comp-dec-modal
output: export/output/coq-comp-dec-modal
tag: '8.20'
packages:
- coq-comp-dec-modal
base_image: theostos/coq-lsp:8.20
opam_env_path: /home/coq/.opam/4.13.1+flambda
user: coq
