name: theostos/coq-extructures
output: export/output/coq-extructures
tag: '9.0'
packages:
- coq-extructures
base_image: theostos/rocq-lsp:9.0
opam_env_path: /home/rocq/.opam/4.14.2+flambda
user: rocq
