name: theostos/coq-math-classes
output: export/output/coq-math-classes
tag: '9.0'
packages:
- coq-math-classes
base_image: theostos/rocq-lsp:9.0
opam_env_path: /home/rocq/.opam/4.14.2+flambda
user: rocq
