name: theostos/coq-libvalidsdp
output: export/output/coq-libvalidsdp
tag: '9.0'
packages:
- coq-libvalidsdp
base_image: theostos/rocq-lsp:9.0
opam_env_path: /home/rocq/.opam/4.14.2+flambda
user: rocq
