name: theostos/coq-library-undecidability
output: export/output/coq-library-undecidability
tag: '8.20'
packages:
- coq-library-undecidability
base_image: theostos/coq-lsp:8.20
opam_env_path: /home/coq/.opam/4.13.1+flambda
user: coq
