name: theostos/coq-graph-theory
output: export/output/coq-graph-theory
tag: '9.0'
packages:
- coq-graph-theory
- coq-graph-theory-planar
base_image: theostos/rocq-lsp:9.0
opam_env_path: /home/rocq/.opam/4.14.2+flambda
user: rocq
