name: theostos/coq-trocq
output: export/output/coq-trocq
tag: '9.0'
packages:
- coq-trocq-hott
- coq-trocq-hott-examples
- coq-trocq-std
- coq-trocq-std-examples
base_image: theostos/rocq-lsp:9.0
opam_env_path: /home/rocq/.opam/4.14.2+flambda
user: rocq
