name: theostos/coq-stdpp
output: export/output/coq-stdpp
tag: '9.0'
packages:
- coq-stdpp
- coq-stdpp-bitvector
base_image: theostos/rocq-lsp:9.0
opam_env_path: /home/rocq/.opam/4.14.2+flambda
user: rocq
