name: theostos/coq-coqprime
output: export/output/coq-coqprime
tag: '9.0'
packages:
- coq-coqprime
- coq-coqprime-generator
base_image: theostos/rocq-lsp:9.0
opam_env_path: /home/rocq/.opam/4.14.2+flambda
user: rocq
