name: theostos/coq-stalmarck
output: export/output/coq-stalmarck
tag: '8.20'
packages:
- coq-stalmarck
- coq-stalmarck-tactic
base_image: theostos/coq-lsp:8.20
opam_env_path: /home/coq/.opam/4.13.1+flambda
user: coq
