name: theostos/coq-qarith-stern-brocot
output: export/output/coq-qarith-stern-brocot
tag: '8.20'
packages:
- coq-qarith-stern-brocot
base_image: theostos/coq-lsp:8.20
opam_env_path: /home/coq/.opam/4.13.1+flambda
user: coq
