name: theostos/rocq-num-analysis
output: export/output/rocq-num-analysis
tag: '9.0'
packages:
- rocq-num-analysis
- rocq-num-analysis-algebra
- rocq-num-analysis-fem
- rocq-num-analysis-lax-milgram
- rocq-num-analysis-lebesgue
- rocq-num-analysis-subset
base_image: theostos/rocq-lsp:9.0
opam_env_path: /home/rocq/.opam/4.14.2+flambda
user: rocq
