name: theostos/rocq-metarocq
output: export/output/rocq-metarocq
tag: '9.0'
packages:
- rocq-metarocq
- rocq-metarocq-common
- rocq-metarocq-erasure
- rocq-metarocq-erasure-plugin
- rocq-metarocq-pcuic
- rocq-metarocq-quotation
- rocq-metarocq-safechecker
- rocq-metarocq-safechecker-plugin
- rocq-metarocq-template
- rocq-metarocq-template-pcuic
- rocq-metarocq-translations
- rocq-metarocq-utils
base_image: theostos/rocq-lsp:9.0
opam_env_path: /home/rocq/.opam/4.14.2+flambda
user: rocq
