name: theostos/rocq-rouche-capelli
output: export/output/rocq-rouche-capelli
tag: '9.0'
packages:
- rocq-rouche-capelli
base_image: theostos/rocq-lsp:9.0
opam_env_path: /home/rocq/.opam/4.14.2+flambda
user: rocq
