name: theostos/rocq-relation-algebra
output: export/output/rocq-relation-algebra
tag: '9.0'
packages:
- rocq-relation-algebra
base_image: theostos/rocq-lsp:9.0
opam_env_path: /home/rocq/.opam/4.14.2+flambda
user: rocq
